docker_pattern_path: /home/euvill/Desktop/docker_ws/src/lidar_localization/config/docker/cloud_cluster_1.pcd
# 匹配
registration_method: NDT   # 选择点云匹配方法，目前支持：NDT 

# 当前帧
frame_filter: voxel_filter # 选择当前帧点云滤波方法，目前支持：voxel_filter、no_filter

# 局部地图
key_frame_distance: 0.005 # 关键帧距离
local_frame_num: 20
local_map_filter: voxel_filter # 选择滑窗地图点云滤波方法，目前支持：voxel_filter、no_filter

# 各配置选项对应参数
## 匹配相关参数
NDT:
    res : 0.05
    step_size : 1e-3
    trans_eps : 1e-3
    max_iter : 60

ICP:
    max_correspondence_distance : 0.1
    max_iter : 30

## 滤波相关参数
voxel_filter:
    local_map:
        leaf_size: [0.01, 0.01, 0.01]
    frame:
        leaf_size: [0.01, 0.01, 0.01]

Docker:
    voxel_filter:
        leaf_size: [0.001, 0.001, 0.001]
    KdTree:
        ClusterTolerance: 0.1 # 10cm
        MinClusterSize: 40
        MaxClusterSize: 120
    MatchParameter:
        FitnessSocre: 0.16
